
device: "cpu" # CPU or CUDA

data_path : "./data/"
model_path: "./data/Model/"
qna_path: "./data/QnA/"
review_path: "./data/Review/"

parameters:
    max_len: 210 # max input length
    batch_size: 16  # batch size on training
    warmup_ratio: 0.1 
    num_epochs: 5 
    max_grad_norm: 1
    log_interval: 200
    learning_rate: 5e-5
    dr_rate: 0.5 # dropout rate
    hidden_size: 768 # BERTClassifier hidden size on training
    num_classes: 5 # number of class
